repos:

-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        args: [
            "--profile=black",
            "--line-length=120"
            ]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: check-toml
    -   id: check-yaml
    -   id: check-json
    -   id: trailing-whitespace
        args: [
            "--markdown-linebreak-ext=md"
            ]

-   repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    -   id: black
        args: [
            "--line-length=120"
            ]

-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        exclude: ^tests/
        args: [
            "--max-line-length=120",
            "--extend-ignore=E203,E501"
            ]

-   repo: https://github.com/pycqa/pylint
    rev: v2.14.1
    hooks:
    -   id: pylint
        exclude: ^tests/
        args: [
            "--max-line-length=120",
            ]
        additional_dependencies:
        -   oauthlib
        -   requests-oauthlib
        -   pytz