repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-toml
    -   id: check-yaml
        args: [
          "--unsafe",
          ]
    -   id: check-json
    -   id: trailing-whitespace
        args: [
            "--markdown-linebreak-ext=md"
            ]

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.261
    hooks:
    -   id: ruff

-   repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
    -   id: black
