repos:

-   repo: https://github.com/pycqa/isort
    rev: 5.6.4
    hooks:
    -   id: isort
        args: [
            "--profile=black",
            "--line-length=120"
            ]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-toml
    -   id: check-yaml
    -   id: check-json
    -   id: trailing-whitespace
        args: [
            "--markdown-linebreak-ext=md"
            ]

-   repo: https://github.com/ambv/black
    rev: 21.9b0
    hooks:
    -   id: black
        args: [
            "--line-length=120"
            ]

-   repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        exclude: ^tests/
        args: [
            "--max-line-length=120",
            "--extend-ignore=E203,E501"
            ]

-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: v3.0.0a4
    hooks:
    -   id: pylint
        exclude: ^tests/
        args: [
            "--max-line-length=120",
            "--disable=
                C0330,
                C0326,
                C0114,
                C0115,
                C0116,
                R0903,
                R1721
                "
            ]
        additional_dependencies:
        -   oauthlib
        -   requests-oauthlib
        -   pytz