name: Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      COVERALLS_FLAG_NAME: python${{ matrix.python-version }}-${{ matrix.os }}
      COVERALLS_PARALLEL: true

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: abatilo/actions-poetry@v2.1.3
        with:
          poetry-version: "1.1.12"
      - run: poetry install
      - run: poetry run tox
      - run: poetry run coveralls --service=github

  submit-coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - run: python -m pip install coverage coveralls toml
      - run: coveralls --service=github --finish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  submit-docs:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - run: python -m pip install mkdocs pymdown-extensions
      - run: mkdocs gh-deploy --force --strict --verbose

